---
title: "Load and explore dataset"
author: "Juan Luis Hernández García"
date: "2024-10-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install dependencies

```{r, results='hide', warning=FALSE}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("SummarizedExperiment")
BiocManager::install("ComplexHeatmap")
```

## Create data container (SummarizedExperiment)

```{r}
library(SummarizedExperiment)

# Load the data
file_path <- "2023-UGrX-4MetaboAnalystTutorial/ST000002_AN000002.txt"
data <- readLines(file_path)

# Parse file sections
metabolite_data_start <- which(data == "MS_METABOLITE_DATA_START") + 1
metabolite_data_end <- which(data == "MS_METABOLITE_DATA_END") - 1
metabolite_table <- data[metabolite_data_start:metabolite_data_end]
metabolite_table <- metabolite_table[-2]

# Convert to data frame
metabolite_df <- read.table(text = metabolite_table, header = TRUE, sep = "\t", row.names = 1)

# Extract sample information
sample_info_start <- which(grepl("#SUBJECT_SAMPLE_FACTORS", data)) + 1
sample_info_end <- which(grepl("#COLLECTION", data)) - 1
sample_info <- data[sample_info_start:sample_info_end]
sample_info <- gsub("\\s+\\t", "\t", sample_info)
sample_info <- gsub("\t-\t", "\t", sample_info)
sample_info <- gsub("\\t$", "", sample_info)
sample_df <- read.table(text = sample_info, sep = "\t", header = FALSE, col.names = c("Subject","Sample", "Factors"))

# Create SummarizedExperiment object
se <- SummarizedExperiment(
  assays = list(counts = as.matrix(metabolite_df)),
  colData = sample_df,
  rowData = DataFrame(metabolite = rownames(metabolite_df))
)

# Display structure
se
```


## Data exploration

```{r}
head(assay(se, "counts"))
```

```{r}
colData(se)
```

```{r}
rowData(se)
```

```{r}
library(ggplot2)

exp_matrix <- assay(se)
lab1 <- exp_matrix["valine", ]
lab2 <- exp_matrix["xanthine", ]

metadata <- rownames(as.data.frame(colData(se)))

df <- data.frame(Lab1 = lab1, Lab2 = lab2, Group = metadata)

ggplot(df, aes(x = Lab1, y = Lab2, color = Group)) +
  geom_point() +
  labs(title = "Relación entre valine y xanthine",
       x = "Expresión de valine", y = "Expresión de xanthine") +
  theme_minimal()

ggsave("relacion.png")
```

```{r}
metabolite <- exp_matrix["uric acid", ]

df <- data.frame(Metabolite = metabolite, Muestras = metadata)

ggplot(df, aes(x = Muestras, y = Metabolite)) +
  geom_point() +
  labs(title = "Acido urico en las distintas muestras",
       x = "Muestra", y = "Acido urico") +
  theme_minimal()

ggsave("muestras.png")
```

## Export data
### Save data and metadata as Rda
```{r}
# Define file paths for saving
se_file <- "intestinal_samples_pre_post_transplantation.Rda"
metadata_file <- "intestinal_samples_pre_post_transplantation_metadata.Rda"

# Save the SummarizedExperiment object
save(se, file = se_file)

# Save the metadata (sample information)
save(sample_df, file = metadata_file)
```

### Save data as text
```{r}
count_matrix <- assay(se)
write.table(count_matrix, file = "metaboliteData.txt", sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)
```

### Save metadata as markdown
```{r}
num_metabolite <- nrow(se)
num_samples <- ncol(se)
assay_names <- assayNames(se)
column_metadata <- colnames(colData(se))
row_metadata <- colnames(rowData(se))
```

```{r}
fileConn <- file("dataset_metadata.md")

cat(
  "# Resumen de Metadatos del Dataset\n\n",
  "## Información General\n",
  "- **Número de metabolitos**: ", num_metabolite, "\n",
  "- **Número de muestras**: ", num_samples, "\n\n",
  
  "## Assays Disponibles\n",
  paste("- ", assay_names, collapse = "\n"), "\n\n",
  
  "## Metadatos de las Muestras (colData)\n",
  paste("- ", column_metadata, collapse = "\n"), "\n\n",
  
  "## Metadatos de los Metabolitos (rowData)\n",
  paste("- ", row_metadata, collapse = "\n"), "\n\n",
  
  "## Ejemplo de Datos\n",
  "### Primeras Filas de la Matriz de Expresión\n\n",
  "```{r}\n",
  paste(capture.output(head(assay(se))), collapse = "\n"),
  "\n```\n\n",
  
  "### Primeras Filas de los Metadatos de las Muestras\n\n",
  "```{r}\n",
  paste(capture.output(head(colData(se))), collapse = "\n"),
  "\n```\n\n",
  
  "### Primeras Filas de los Metadatos de los Metabolitos\n\n",
  "```{r}\n",
  paste(capture.output(head(rowData(se))), collapse = "\n"),
  "\n```\n\n",
  
  file = fileConn
)

close(fileConn)

```

